=== alwintje/xml/together/garages.dtd
<!--
 + 1 OF MEER
 * 0 OF MEER
 ? 0 OF 1
-->
<!-- Collectie alle garages -->
<!ELEMENT GARAGES (GARAGE+)>

<!-- Alle categoriÃ«n van een garage zijn:
    -   Naam.
    -   Adresgegevens.
    -   Telefoonnummer.
    -   Email.
    -   Website (optioneel).
    -   Verkoop, dit gaat om de verkoop van auto's.
    -   Werkplaats, beschrijft de openingstijden en werkzaamheden van de werkplaats.
    -   Certificaten, beschrijft de certificering van de garages.
    -   Medewerkers, beschrijft de medewerkers van de garages.
    -   Faciliteiten, dit bevat alle overige services die de garages kunnen bieden met o.a. wasstraten en pompen.
    -->
<!ELEMENT GARAGE (NAAM, ADRESGEGEVENS, TELEFOONNUMMER, EMAIL, WEBSITE?, VERKOOP, WERKPLAATS, CERTIFICATEN?, MEDEWERKERS, FACILITEITEN?)>

<!-- Alle contactgegevens van de garage -->
<!ELEMENT NAAM (#PCDATA)>
<!ELEMENT EMAIL (#PCDATA)>
<!ELEMENT TELEFOONNUMMER (#PCDATA)>
<!ELEMENT WEBSITE (#PCDATA)>
<!ELEMENT ADRESGEGEVENS (STRAAT, HUISNUMMER, POSTCODE, PLAATS, PROVINCIE)>
<!ELEMENT STRAAT (#PCDATA)>
<!ELEMENT HUISNUMMER (#PCDATA)>
<!ELEMENT POSTCODE (#PCDATA)>
<!ELEMENT PLAATS (#PCDATA)>
<!ELEMENT PROVINCIE (#PCDATA)>

<!-- Autoverkoop van de garage algemene informatie-->
<!ELEMENT VERKOOP (OPENINGSTIJDEN, DIENSTEN?, (NIEUWE-AUTOS?, OCCASIONS?))>
<!ELEMENT OPENINGSTIJDEN (ZONDAG?, MAANDAG?, DINSDAG?, WOENSDAG?, DONDERDAG?, VRIJDAG?, ZATERDAG?)>
<!ENTITY % TIJDEN "(OPENING, SLUITING)+">

<!-- Voor alle dagen wordt minimaal een openingstijd en een sluitingstijd opgeslagen -->
<!ELEMENT ZONDAG %TIJDEN;>
<!ELEMENT MAANDAG %TIJDEN;>
<!ELEMENT DINSDAG %TIJDEN;>
<!ELEMENT WOENSDAG %TIJDEN;>
<!ELEMENT DONDERDAG %TIJDEN;>
<!ELEMENT VRIJDAG %TIJDEN;>
<!ELEMENT ZATERDAG %TIJDEN;>
<!ELEMENT OPENING (#PCDATA)>
<!ELEMENT SLUITING (#PCDATA)>

<!-- Verhuur en leenservice -->
<!ELEMENT DIENSTEN (VERHUUR?, LENEN?)>
<!ELEMENT VERHUUR EMPTY>
<!ELEMENT LENEN EMPTY>

<!-- Nieuwe en/of gebruikte auto's -->
<!ELEMENT NIEUWE-AUTOS (AUTO+)>
<!ELEMENT OCCASIONS (AUTO+)

<!-- Auto gegevens -->
<!ELEMENT AUTO (MODEL, BOUWJAAR, BRANDSTOF, PRIJS, APK-VERLOOP-DATUM, FOTOS)>
<!ATTLIST AUTO kenteken CDATA>
<!ATTLIST AUTO merk (Alfa_Romeo AMC Asia Aston_Martin Audi Austin Autobianchi Bedford Bentley Bitter BMW Brilliance Bugatti Buick Cadillac Chevrolet Chrysler Citroen Dacia Daewoo DAF Daihatsu Diversen Dodge Ferrari Fiat Fisker Ford Ford_Usa FSO GMC Honda Hummer Hyundai Infiniti Innocenti Isuzu Iveco Jaguar Jeep Kia Lada Lamborghini Lancia Landrover Landwind LDV Lexus Leyland Lotus MAN Maserati Maybach Mazda Mercedes MG Mini Mitsubishi Morris Nissan NSU Oldsmobile Opel Peugeot PGO Piaggio Plymouth Pontiac Porsche Proton Reliant Renault Rolls_Royce Rover Saab Seat Skoda Smart Ssang Yong Subaru Sunbeam Suzuki Talbot Tata Tesla Toyota Trabant Triumph TVR Vauxhall Volkswagen Volvo Xedos Yue Loong Zastava) #REQUIRED>
<!-- MERKEN LIJST
    -   Alfa Romeo
    -   AMC
    -   Asia
    -   Aston Martin
    -   Audi
    -   Austin
    -   Autobianchi
    -   Bedford
    -   Bentley
    -   Bitter
    -   BMW
    -   Brilliance
    -   Bugatti
    -   Buick
    -   Cadillac
    -   Chevrolet
    -   Chrysler
    -   Citroen
    -   Dacia
    -   Daewoo
    -   DAF
    -   Daihatsu
    -   Diversen
    -   Dodge
    -   Ferrari
    -   Fiat
    -   Fisker
    -   Ford
    -   Ford Usa
    -   FSO
    -   GMC
    -   Honda
    -   Hummer
    -   Hyundai
    -   Infiniti
    -   Innocenti
    -   Isuzu
    -   Iveco
    -   Jaguar
    -   Jeep
    -   Kia
    -   Lada
    -   Lamborghini
    -   Lancia
    -   Landrover
    -   Landwind
    -   LDV
    -   Lexus
    -   Leyland
    -   Lotus
    -   MAN
    -   Maserati
    -   Maybach
    -   Mazda
    -   Mercedes
    -   MG
    -   Mini
    -   Mitsubishi
    -   Morris
    -   Nissan
    -   NSU
    -   Oldsmobile
    -   Opel
    -   Peugeot
    -   PGO
    -   Piaggio
    -   Plymouth
    -   Pontiac
    -   Porsche
    -   Proton
    -   Reliant
    -   Renault
    -   Rolls Royce
    -   Rover
    -   Saab
    -   Seat
    -   Skoda
    -   Smart
    -   Ssang Yong
    -   Subaru
    -   Sunbeam
    -   Suzuki
    -   Talbot
    -   Tata
    -   Tesla
    -   Toyota
    -   Trabant
    -   Triumph
    -   TVR
    -   Vauxhall
    -   Volkswagen
    -   Volvo
    -   Xedos
    -   Yue Loong
    -   Zastava
    -->
<!ELEMENT MODEL (#PCDATA)>
<!ELEMENT BOUWJAAR (#PCDATA)>
<!ELEMENT BRANDSTOF EMPTY>
<!--
    Verschillende brandstoffen zijn gedefninieerd
    -   Euro_95
    -   LPG
    -   DIESEL
    -   CNG
    -   Super_plus
    -   Super_MLV
    -   Premium_benzine
    -   Premium_diesel
    -->
<!ATTLIST BRANDSTOF naam (Euro_95 LPG Diesel CNG Super_Plus Super_MLV Premium_Benzine Premium_Diesel) #REQUIRED>
<!ELEMENT PRIJS (#PCDATA)>

<!-- APK DATUM AUTO's EN FOTO's-->
<!ELEMENT APK-VERLOOP-DATUM (#PCDATA)>
<!ELEMENT FOTOS (FOTO+)>
<!ELEMENT FOTO (URL, ALT)>
<!ELEMENT URL (#PCDATA)>
<!ELEMENT ALT (#PCDATA)>


<!ELEMENT WERKPLAATS (OPENINGSTIJDEN, WERKZAAMHEDEN)>
<!-- OPENINGSTIJDEN IS AL GEDEFINEERD -->
<!ELEMENT WERKZAAMHEDEN (ONDERHOUD?, APK?, SCHADEHERSTEL?, RUITENREPARATIE?, AIRCOSERVICE?, BANDENSERVICE?)>

<!-- Verschillende werkzaamheden die in de werkplaats gedaan kunnen worden -->
<!ELEMENT ONDERHOUD EMPTY>
<!ELEMENT APK EMPTY>
<!ELEMENT SCHADEHERSTEL EMPTY>
<!ELEMENT RUITENREPARATIE EMPTY)>
<!ELEMENT AIRCOSERVICE EMPTY>
<!ELEMENT BANDENSERVICE EMPTY)>

<!-- Verschillende mogelijke certificaten, lege velden geven aan of het wel of niet bestaat -->
<!ELEMENT CERTIFICATEN (BOVAG?, RDW?)>
<!ELEMENT BOVAG EMPTY>
<!ELEMENT RDW EMPTY>

<!-- Medewerkers van het bedrijf met foto en functie-->
<!ELEMENT MEDEWERKERS (MEDEWERKER+)>
<!ELEMENT MEDEWERKER (VOORNAAM,TUSSENVOEGSEL?,ACHTERNAAM,FOTO,FUNCTIE)>
<!ELEMENT VOORNAAM (#PCDATA)>
<!ELEMENT TUSSENVOEGSEL (#PCDATA)>
<!ELEMENT ACHTERNAAM (#PCDATA)>
<!-- FOTO IS AL GEDEFINEERD -->
<!ELEMENT FUNCTIE EMPTY>
<!ATTLIST FUNCTIE naam (Eigenaar Medewerker Monteur Verkoper Telefonist) #REQUIRED >

<!-- Overige faciliteiten die de winkel kan hebben -->
<!ELEMENT FACILITEITEN (POMPEN?, WASSEN?, WINKEL?)>
<!ELEMENT POMPEN (POMP+, BRANDSTOF-PRIJZEN)>
<!ELEMENT POMP (BRANDSTOFFEN*)>
<!ATTLIST POMP nummer CDATA #REQUIRED>
<!ELEMENT BRANDSTOFFEN (BRANDSTOF+)>
<!-- BRANDSTOF IS AL GEDEFINEERD -->

<!ELEMENT BRANDSTOF-PRIJZEN (BRANDSTOF-PRIJS+)>
<!ELEMENT BRANDSTOF-PRIJS (BRANDSTOF, PRIJS)>
<!-- BRANDSTOF IS AL GEDEFINEERD -->
<!-- PRIJS IS AL GEDEFINEERD -->

<!ELEMENT WASSEN (WASSTRATEN?, WASBOXEN?)>
<!ELEMENT WASSTRATEN (WASSTRAAT+)>
<!ELEMENT WASSTRAAT (PRIJS)>
<!-- PRIJS IS AL GEDEFINEERD -->

<!ELEMENT WASBOXEN (WASBOX+)>
<!ELEMENT WASBOX (PRIJS)>
<!-- PRIJS IS AL GEDEFINEERD -->

<!ELEMENT WINKEL (LEVENSMIDDELEN?, ROOKWAAR?, TIJDSCHRIFTEN?, AUTO-ACCESOIRES?)>
<!-- Alle mogelijke producttypen die een winkel kan hebben -->
<!ELEMENT LEVENSMIDDELEN (#PCDATA)>
<!ELEMENT ROOKWAAR (#PCDATA)>
<!ELEMENT TIJDSCHRIFTEN (#PCDATA)>
<!ELEMENT AUTO-ACCESOIRES (#PCDATA)>

=== alwintje/xml/jose/garages.xml
<?xml version="1.0" encoding="UTF-8"?>


<!DOCTYPE GARAGES SYSTEM "..\together\garages.dtd">

<GARAGES>
    <GARAGE>
        <NAAM>Garage Westerink B.V.</NAAM>
        <ADRESGEGEVENS>
            <STRAAT>Westeinde</STRAAT>
            <HUISNUMMER>106</HUISNUMMER>
            <POSTCODE>3844 DR</POSTCODE>
            <PLAATS>Harderwijk</PLAATS>
            <PROVINCIE>Gelderland</PROVINCIE>
        </ADRESGEGEVENS>
        <TELEFOONNUMMER>0341 431 188</TELEFOONNUMMER>
        <EMAIL>info@vakgaragewesterink.nl</EMAIL>
        <VERKOOP>
            <OPENINGSTIJDEN>
                <MAANDAG>
                    <OPENINGSTIJDEN>9:00</OPENINGSTIJDEN>
                    <SLUITINGSTIJDEN>18:00</SLUITINGSTIJDEN>
                </MAANDAG>
                <DINSDAG>
                    <OPENINGSTIJDEN>9:00</OPENINGSTIJDEN>
                    <SLUITINGSTIJDEN>18:00</SLUITINGSTIJDEN>
                </DINSDAG>
                <WOENSDAG>
                    <OPENINGSTIJDEN>9:00</OPENINGSTIJDEN>
                    <SLUITINGSTIJDEN>18:00</SLUITINGSTIJDEN>
                </WOENSDAG>
                <DONDERDAG>
                    <OPENINGSTIJDEN>9:00</OPENINGSTIJDEN>
                    <SLUITINGSTIJDEN>18:00</SLUITINGSTIJDEN>
                </DONDERDAG>
                <VRIJDAG>
                    <OPENINGSTIJDEN>9:00</OPENINGSTIJDEN>
                    <SLUITINGSTIJDEN>18:00</SLUITINGSTIJDEN>
                </VRIJDAG>
                <ZATERDAG>
                    <OPENINGSTIJDEN>9:00</OPENINGSTIJDEN>
                    <SLUITINGSTIJDEN>17:00</SLUITINGSTIJDEN>
                </ZATERDAG>
                <ZONDAG>
                    <OPENINGSTIJDEN>Gesloten</OPENINGSTIJDEN>
                    <SLUITINGSTIJDEN>Gesloten</SLUITINGSTIJDEN>
                </ZONDAG>
            </OPENINGSTIJDEN>
            <DIENSTEN>
                <VERHUUR>Nee</VERHUUR>
                <LENEN>Nee</LENEN>
            </DIENSTEN>
            <AUTOS>
                <AUTO kenteken="XX-RR22-12">
                    <NIEUW>Ja</NIEUW>
                    <MERK>MITSUBISHI</MERK>
                    <TYPE>SPACE STAR COOL+</TYPE>
                    <BOUWJAAR>2017</BOUWJAAR>
                    <BRANDSTOF>Diesel</BRANDSTOF>
                    <PRIJS>176</PRIJS>
                    <DATUM>12-02-2015</DATUM>
                    <APK-VERLOOP-DATUM>12-02-2020</APK-VERLOOP-DATUM>
                    <FOTOS>
                        <FOTO>E:\Users\jose_\Desktop\Stenden\jaar 2\periode 3\XML\Space-Star---website-900x900---V3.png</FOTO>
                    </FOTOS>
                </AUTO>
            </AUTOS>
        </VERKOOP>
        <WERKPLAATS>
            <OPENINGSTIJDEN></OPENINGSTIJDEN>
            <WERKZAAMHEDEN>
                <ONDERHOUD></ONDERHOUD>
                <APK></APK>
                <SCHADEHERSTEL></SCHADEHERSTEL>
                <RUITENREPARATIE></RUITENREPARATIE>
                <AIRCOSERVICE></AIRCOSERVICE>
                <BANDENSERVICE></BANDENSERVICE>
            </WERKZAAMHEDEN>
        </WERKPLAATS>
        <CERTIFICATEN></CERTIFICATEN>
        <MEDEWERKERS>
            <MEDEWERKER>
                <VOORNAAM></VOORNAAM>
                <ACHTERNAAM></ACHTERNAAM>
                <FOTO></FOTO>
                <FUNCTIE></FUNCTIE>
            </MEDEWERKER>
        </MEDEWERKERS>
        <FACILITEITEN></FACILITEITEN>
    </GARAGE>
</GARAGES>

=== alwintje/xml/kevin/garages.xml
<?xml version="1.0" encoding="UTF-8"?>


<!DOCTYPE GARAGES SYSTEM "..\together\garages.dtd">

<GARAGES>
  <GARAGE>
    <NAAM>Garage de koning</NAAM>
    <ADRESGEGEVENS>
      <STRAAT>Herenstraat</STRAAT>
      <HUISNUMMER>33</HUISNUMMER>
      <POSTCODE>9402XS</POSTCODE>
      <PLAATS>Groningen</PLAATS>
      <PROVINCIE>Groningen</PROVINCIE>
    </ADRESGEGEVENS>
    <TELEFOONNUMMER>0468-686841</TELEFOONNUMMER>
    <EMAIL>contact@garagedeKoning.nl</EMAIL>
    <VERKOOP>
      <OPENINGSTIJDEN>
        <MAANDAG>
          <OPENING>08:00</OPENING>
          <SLUITING>17:30</SLUITING>
        </MAANDAG>
        <DINSDAG>
          <OPENING>08:00</OPENING>
          <SLUITING>17:30</SLUITING>
        </DINSDAG>
        <WOENSDAG>
          <OPENING>08:00</OPENING>
          <SLUITING>17:00</SLUITING>
        </WOENSDAG>
        <DONDERDAG>
          <OPENING>08:00</OPENING>
          <SLUITING>17:00</SLUITING>
        </DONDERDAG>
        <VRIJDAG>
          <OPENING>08:00</OPENING>
          <SLUITING>17:00</SLUITING>
        </VRIJDAG>
        <ZATERDAG>
          <OPENING>10:00</OPENING>
          <SLUITING>16:00</SLUITING>
        </ZATERDAG>
      </OPENINGSTIJDEN>
      <DIENSTEN>
        <VERHUUR>JA</VERHUUR>
        <LENEN>JA</LENEN>
      </DIENSTEN>
      <AUTOS>
        <AUTO kenteken="26-NTT-2">
          <NIEUW>true</NIEUW>
          <MERK>Porsche</MERK>
          <TYPE>Cayenne 2s</TYPE>
          <BOUWJAAR>2018</BOUWJAAR>
          <BRANDSTOF>Diesel</BRANDSTOF>
          <PRIJS>98000,00</PRIJS>
          <DATUM>1-4-2018</DATUM>
          <APK-VERLOOP-DATUM>1-4-2020</APK-VERLOOP-DATUM>
          <FOTOS>
            <FOTO>cayenne2sFront.jpg</FOTO>
            <FOTO>cayenne2sSide.jpg</FOTO>
            <FOTO>cayenne2sPromo.jpg</FOTO>
          </FOTOS>
        </AUTO>
        <AUTO kenteken="99-XDR-4">
          <NIEUW>true</NIEUW>
          <MERK>Audi</MERK>
          <TYPE>A3</TYPE>
          <BOUWJAAR>2018</BOUWJAAR>
          <BRANDSTOF>Benzine</BRANDSTOF>
          <PRIJS>58000,00</PRIJS>
          <DATUM>26-2-2017</DATUM>
          <APK-VERLOOP-DATUM>26-2-2019</APK-VERLOOP-DATUM>
          <FOTOS>
            <FOTO>A3Front.jpg</FOTO>
            <FOTO>A3side.jpg</FOTO>
            <FOTO>A3inside.jpg</FOTO>
          </FOTOS>
      </AUTOS>
    </VERKOOP>
    <WERKPLAATS>
      <OPENINGSTIJDEN>
        <MAANDAG>
          <OPENING>08:00</OPENING>
          <SLUITING>17:30</SLUITING>
        </MAANDAG>
        <DINSDAG>
          <OPENING>08:00</OPENING>
          <SLUITING>17:30</SLUITING>
        </DINSDAG>
        <WOENSDAG>
          <OPENING>08:00</OPENING>
          <SLUITING>17:00</SLUITING>
        </WOENSDAG>
        <DONDERDAG>
          <OPENING>08:00</OPENING>
          <SLUITING>17:00</SLUITING>
        </DONDERDAG>
        <VRIJDAG>
          <OPENING>08:00</OPENING>
          <SLUITING>17:00</SLUITING>
        </VRIJDAG>
        <ZATERDAG>
          <OPENING>10:00</OPENING>
          <SLUITING>16:00</SLUITING>
        </ZATERDAG>
      </OPENINGSTIJDEN>
      <WERKZAAMHEDEN>
        <ONDERHOUD>true</ONDERHOUD>
        <APK>true</APK>
        <SCHADEHERSTEL>false</SCHADEHERSTEL>
        <RUITENREPARATIE>false</RUITENREPARATIE>
        <AIRCOSERVICE>false</AIRCOSERVICE>
        <BANDENSERVICE>true</BANDENSERVICE>
      </WERKZAAMHEDEN>
    </WERKPLAATS>
    <CERTIFICATEN>
      <CERTIFICAAT>BOVAG</CERTIFICAAT>
      <CERTIFICAAT>Bandenspecialist</CERTIFICAAT>
    </CERTIFICATEN>
    <MEDEWERKERS>
      <MEDEWERKER>
        <VOORNAAM>Henry</VOORNAAM>
        <ACHTERNAAM>Ottersma</ACHTERNAAM>
        <FUNCTIE>Bandenvervanger</FUNCTIE>
      </MEDEWERKER>
      <MEDEWERKER>
        <VOORNAAM>Dave</VOORNAAM>
        <ACHTERNAAM>Meesters</ACHTERNAAM>
        <FOTO>Dmeesters.jpg</FOTO>
        <FUNCTIE>Monteur</FUNCTIE>
      </MEDEWERKER>
      <MEDEWERKER>
        <VOORNAAM>Henk</VOORNAAM>
        <ACHTERNAAM>Meesters</ACHTERNAAM>
        <FOTO>Hmeesters.jpg</FOTO>
        <FUNCTIE>Manager</FUNCTIE>
      </MEDEWERKER>
    </MEDEWERKERS>
    <FACILITEITEN>
      <POMPEN>
        <POMP nummer="1">
          <BRANDSTOFFEN>
            <BRANDSTOF>
              <NAAM>Diesel</NAAM>
              <PRIJS>1.31</PRIJS>
            </BRANDSTOF>
            <BRANDSTOF>
              <NAAM>Benzine</NAAM>
              <PRIJS>1.51</PRIJS>
            </BRANDSTOF>
          </BRANDSTOFFEN>
        </POMP>
        <POMP nummer="2">
          <BRANDSTOFFEN>
            <BRANDSTOF>
              <NAAM>Diesel</NAAM>
              <PRIJS>1.31</PRIJS>
            </BRANDSTOF>
            <BRANDSTOF>
              <NAAM>Benzine</NAAM>
              <PRIJS>1.51</PRIJS>
            </BRANDSTOF>
          </BRANDSTOFFEN>
        </POMP>
      </POMPEN>
    </FACILITEITEN>
  </GARAGE>
</GARAGES>
