=== alwintje/xml/boeken.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="library">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="book">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string" />
                            <xs:element name="isbn">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="\d{3}-\d{1}-\d{3}-\d{5}-\d{1}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="release_date" type="xs:date" />
                            <xs:element name="score">
                                <xs:simpleType>
                                    <xs:restriction base="xs:decimal">
                                        <xs:minInclusive value="0"/>
                                        <xs:maxInclusive value="10"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== alwintje/xml/boeken.xml
<?xml version='1.0' encoding='UTF-8' standalone='no'?>

<library xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="boeken.xsd">
    <book>
        <name>Embedded Systems - Micro en C</name>
        <isbn>978-9-048-40835-1</isbn>
        <release_date>2011-09-02</release_date>
        <score>6.2</score>
    </book>
    <book>
        <name>TMap NEXT(r) - Sogeti</name>
        <isbn>827-2-122-99192-8</isbn>
        <release_date>2008-08-10</release_date>
        <score>9.8</score>
    </book>
    <book>
        <name>The Hobbit</name>
        <isbn>583-3-121-48410-5</isbn>
        <release_date>2001-11-09</release_date>
        <score>9</score>
    </book>
    <book>
        <name>Hannibal</name>
        <isbn>986-3-161-48410-0</isbn>
        <release_date>2001-07-13</release_date>
        <score>8.3</score>
    </book>
</library>
