=== alwintje/xml/CDs.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="cds">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="cd"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="cd">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="id"/>
                <xs:element ref="naam"/>
                <xs:element ref="uitvoerenden"/>
                <xs:element ref="uitgever"/>
                <xs:element ref="gerne"/>
                <xs:element ref="prijs"/>
                <xs:element ref="releaseDate"/>
                <xs:element ref="boxVolume"/>
                <xs:element ref="tracks"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="id" type="xs:integer"/>
    <xs:element name="uitvoerenden">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="uitvoerende"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="uitgever" type="xs:string"/>
    <xs:element name="gerne" type="xs:NCName"/>
    <xs:element name="prijs">
        <xs:complexType mixed="true">
            <xs:attribute name="format" use="required" type="xs:NCName"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="releaseDate">
        <xs:complexType mixed="true">
            <xs:attribute name="format" use="required" type="xs:NCName"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="boxVolume" type="xs:integer"/>
    <xs:element name="tracks">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="track"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="track">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="naam"/>
                <xs:element ref="componisten"/>
                <xs:element ref="tijdsduur"/>
                <xs:element ref="uitvoerende"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="componisten">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="componist"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="componist" type="xs:string"/>
    <xs:element name="tijdsduur">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:NMTOKEN">
                    <xs:attribute name="format" use="required" type="xs:NMTOKEN"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="naam" type="xs:string"/>
    <xs:element name="uitvoerende" type="xs:string"/>
</xs:schema>

=== alwintje/xml/CDs.xml
<?xml version="1.0"?>
<!DOCTYPE cds SYSTEM "cds.dtd">

<cds xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="CDs.xsd">
    <cd>
        <id>1</id>
        <naam>Advenge sevenfold The stage</naam>
        <uitvoerenden>
            <uitvoerende>Advenge sevenfold</uitvoerende>
        </uitvoerenden>
        <uitgever>United Recording studio</uitgever>
        <gerne>Rock</gerne>
        <prijs format="euro">14,99</prijs>
        <releaseDate format="date">October 28, 2016</releaseDate>
        <boxVolume>1</boxVolume>
        <tracks>
            <track>
                <naam>The stage</naam>
                <componisten>
                    <componist>Advange</componist>
                </componisten>
                <tijdsduur format="mm:ss">8:10</tijdsduur>
                <uitvoerende>-</uitvoerende>
            </track>
            <track>
                <naam>Paradigim</naam>
                <componisten>
                    <componist>Advange</componist>
                </componisten>
                <tijdsduur format="mm:ss">4:18</tijdsduur>
                <uitvoerende>-</uitvoerende>
            </track>
            <track>
                <naam>God Damn</naam>
                <componisten>
                    <componist>Advange</componist>
                </componisten>
                <tijdsduur format="mm:ss">6:18</tijdsduur>
                <uitvoerende>-</uitvoerende>
            </track>
        </tracks>
    </cd>

    <cd>
        <id>2</id>
        <naam>Foo fighters</naam>
        <uitvoerenden>
            <uitvoerende>Foo fighterrs</uitvoerende>
        </uitvoerenden>
        <uitgever>United ASD studio</uitgever>
        <gerne>Rock</gerne>
        <prijs format="euro">14,99</prijs>
        <releaseDate format="date">October 28, 2016</releaseDate>
        <boxVolume>1</boxVolume>
        <tracks>
            <track>
                <naam>Something for nothing</naam>
                <componisten>
                    <componist>Foo fighters</componist>
                </componisten>
                <tijdsduur format="mm:ss">3:55</tijdsduur>
                <uitvoerende>-</uitvoerende>
            </track>
            <track>
                <naam>Outside</naam>
                <componisten>
                    <componist>Foo fighters</componist>
                </componisten>
                <tijdsduur format="mm:ss">3:33</tijdsduur>
                <uitvoerende>-</uitvoerende>
            </track>
        </tracks>
    </cd>

    <cd>
        <id>3</id>
        <naam>The Black keys</naam>
        <uitvoerenden>
            <uitvoerende>The blackkeys</uitvoerende>
        </uitvoerenden>
        <uitgever>United belgian studio</uitgever>
        <gerne>Rock</gerne>
        <prijs format="euro">14,99</prijs>
        <releaseDate format="date">October 28, 2016</releaseDate>
        <boxVolume>1</boxVolume>
        <tracks>
            <track>
                <naam>Next girl</naam>
                <componisten>
                    <componist>Advange</componist>
                </componisten>
                <tijdsduur format="mm:ss">3:55</tijdsduur>
                <uitvoerende>-</uitvoerende>
            </track>
            <track>
                <naam>These days</naam>
                <componisten>
                    <componist>The black keys</componist>
                </componisten>
                <tijdsduur format="mm:ss">3:33</tijdsduur>
                <uitvoerende>-</uitvoerende>
            </track>
        </tracks>
    </cd>

</cds>
