=== alwintje/xml/schaakbord.dtd
<?xml version="1.0" encoding="UTF-8"?>

        <!ENTITY % stukken "(koning,koningin?,loper?,loper?,toren?, toren?,paard?, paard?,pion?,pion?, pion?, pion?,pion?,pion?, pion?, pion?)">

        <!ENTITY % positie "(column CDATA #REQUIRED '' row CDATA #REQUIRED)">p

        <!ELEMENT xml (schaakbord)>
        <!ATTLIST xml
                xmlns CDATA #FIXED ''>

        <!ELEMENT schaakbord (wit,zwart)>
        <!ATTLIST schaakbord>

        <!ELEMENT wit %stukken;>
        <!ATTLIST wit
                xmlns CDATA #FIXED ''>

        <!ELEMENT zwart %stukken; >
        <!ATTLIST zwart
                xmlns CDATA #FIXED ''>

        <!ELEMENT koning EMPTY>
        <!ATTLIST koning %positie;>

        <!ELEMENT koningin EMPTY>
        <!ATTLIST koningin %positie;>

        <!ELEMENT loper EMPTY>
        <!ATTLIST loper %positie;>

        <!ELEMENT toren EMPTY>
        <!ATTLIST toren %positie;>

        <!ELEMENT paard EMPTY>
        <!ATTLIST paard %positie;>

        <!ELEMENT pion EMPTY>
        <!ATTLIST pion %positie;>

=== alwintje/xml/Schaakbord.xml
<xml version="1.0" encoding="UTF-8">
<!DOCTYPE schaakbord SYSTEM "schaakbord.dtd">
    <schaakbord>
        <wit>
            <koning column="F" row="1"></koning>
            <koningin column="G" row="1"></koningin>
            <loper column="D" row="1"></loper>
            <loper column="G" row="2"></loper>
            <toren column="B" row="1"></toren>
            <toren column="F" row="4"></toren>
            <paard column="E" row="2"></paard>
            <paard column="D" row="4"></paard>
            <pion column="H" row="2"></pion>
            <pion column="G" row="3"></pion>
            <pion column="E" row="4"></pion>
            <pion column="B" row="3"></pion>
            <pion column="A" row="2"></pion>
        </wit>
        <zwart>
            <koning column="H" row="8"></koning>
            <koningin column="A" row="5"></koningin>
            <loper column="E" row="7"></loper>
            <loper column="D" row="7"></loper>
            <toren column="F" row="8"></toren>
            <toren column="C" row="8"></toren>
            <paard column="F" row="6"></paard>
            <paard column="C" row="6"></paard>
            <pion column="H" row="7"></pion>
            <pion column="G" row="7"></pion>
            <pion column="F" row="7"></pion>
            <pion column="E" row="6"></pion>
            <pion column="D" row="6"></pion>
        </zwart>
    </schaakbord>
</xml>
